### PR TITLE
Upgrade dep to 1.0.20 and version bump

### PR DESCRIPTION
**Pull request by neiljaywarner**

### CODE REVIEW

**Comment by neiljaywarner** [comment]
@umair13adil  my CI/CD pipeline is passing now with this change.

**Comment by willyfromtheblock** [comment]
Some heroes don't wear capes.

**Comment by neiljaywarner** [comment]
see #55

**Comment by Myzel394** [comment]
Is this library even maintained by @umair13adil ? The last commit is from last year...

**Comment by leejonggun** [comment]
Thank you a lot @umair13adil @neiljaywarner. I am waiting for PR is merged when ready :)

**Comment by umair13adil** [comment]
@leejonggun PR is merged, new version is now available. flutter_logs: ^2.1.11

**Pull request merged**
